#!/usr/bin/env node
/* project-doc integrity checker — LOCKED.
   Usage: node check.mjs <path-to-index.html>
   Mechanises the "Integrity checks before writing" list in update-protocol.md.
   Regex-based on purpose: the document is machine-generated by this skill, so
   its markup is regular enough to check without a DOM parser or a dependency.
   Exit 0 = clean. Exit 1 = at least one error. Warnings never fail the run. */

import { readFileSync } from 'node:fs';
import { validateData } from './doc-data-check.mjs';

const path = process.argv[2];
if (!path) { console.error('usage: node check.mjs <path-to-index.html>'); process.exit(2); }
const html = readFileSync(path, 'utf8');

const errors = [];
const warns = [];
const err = (m) => errors.push(m);
const warn = (m) => warns.push(m);
const count = (re) => (html.match(re) || []).length;

// {JSON BLOCKS}
function jsonBlock(id) {
  const m = html.match(new RegExp(
    `<script type="application/json" id="${id}">([\\s\\S]*?)</script>`));
  if (!m) return { present: false, value: null };
  try { return { present: true, value: JSON.parse(m[1]) }; }
  catch { err(`#${id} does not parse as JSON (an unescaped </script inside it truncates the block)`); return { present: true, value: null }; }
}
const cfg = jsonBlock('doc-config');
if (!cfg.present) err('no #doc-config block — runtime dates will render in the reader\'s zone');
else if (cfg.value && !cfg.value.timezone) err('#doc-config has no "timezone"');
const allow = jsonBlock('doc-allowlist');
if (!allow.present) err('no #doc-allowlist block');
else if (allow.value && !Array.isArray(allow.value)) err('#doc-allowlist is not an array');
const prev = jsonBlock('doc-previews');
// build the preview key set once (accepts the keyed object or the legacy array)
let previews = {};
if (prev.value && Array.isArray(prev.value.citations)) {
  for (const c of prev.value.citations) if (c && c.key) previews[c.key] = c;
  warn('#doc-previews uses the legacy citations-array shape — emit the keyed object');
} else if (prev.value) previews = prev.value;

// cursors and everything else the next run needs live INLINE in the document —
// the published Artifact is the single source of truth, so #doc-state travels
// with the page, not in a sidecar file that a fresh clone would never have.
const state = jsonBlock('doc-state');

// {DOC-DATA} — the source of truth. Its shape and cross-refs are validated here,
// BEFORE the rendered HTML is trusted; the HTML checks further down are the
// post-render sanity pass (sprites resolve, hosts allowlisted, links land). A
// format-3 document carries #doc-data; a legacy format-2 document does not.
const data = jsonBlock('doc-data');
const expectFormat = data.present ? 3 : 2;
if (!state.present) err('no #doc-state block — cursors must be inline (the Artifact is the state)');
else if (state.value) {
  if (state.value.format !== expectFormat) err(`#doc-state format is ${state.value.format}, expected ${expectFormat}`);
  if (!state.value.cursors) err('#doc-state has no "cursors"');
}
if (data.present && data.value) {
  const r = validateData(data.value, previews);
  for (const e of r.errors) err(e);
  for (const w of r.warns) warn(w);
}

// {IDS AND ANCHORS}
const ids = new Set();
for (const m of html.matchAll(/ id="([^"]+)"/g)) {
  if (ids.has(m[1])) err(`duplicate id "${m[1]}"`);
  ids.add(m[1]);
}
for (const m of html.matchAll(/href="#([^"]+)"/g)) {
  const id = decodeURIComponent(m[1]);
  if (!ids.has(id)) err(`href="#${m[1]}" resolves to no id`);
}
for (const m of html.matchAll(/aria-controls="([^"]+)"/g)) {
  if (!ids.has(m[1])) err(`aria-controls="${m[1]}" resolves to no id`);
}

// {SPRITES}
const symbols = new Set([...html.matchAll(/<symbol[^>]* id="([^"]+)"/g)].map((m) => m[1]));
if (!symbols.size) err('no <symbol> definitions — were the two sprites inlined?');
for (const m of html.matchAll(/<use href="#([^"]+)"/g)) {
  if (!symbols.has(m[1])) err(`<use href="#${m[1]}"> resolves to no symbol`);
}

// {STRUCTURE}
const latest = count(/class="[^"]*\bis-latest\b[^"]*"/g);
if (latest !== 1) err(`${latest} elements carry is-latest, expected exactly 1`);
if (/doc-mast/.test(html)) err('a .doc-mast survives — there is no masthead');
if (/class="tabs"/.test(html)) err('the old horizontal .tabs survives');
const au = state.value && state.value.artifactUrl;
if (au && !/^https:\/\//.test(au)) err('#doc-state artifactUrl is not an https URL');
if (count(/class="src-note"/g) !== 1) err(`${count(/class="src-note"/g)} .src-note elements, expected exactly 1 (last element of #whatsnew)`);
const dn = count(/class="dial-name"/g);
if (dn !== 1) err(`${dn} .dial-name elements, expected exactly 1`);

// {DIAL}
const tabCount = count(/role="tab"(?!list|panel)/g);
const panelCount = count(/role="tabpanel"/g);
if (tabCount !== panelCount) err(`${tabCount} tabs but ${panelCount} panels`);
if (count(/aria-selected="true"/g) !== 1) err('aria-selected="true" must appear exactly once');
if (/aria-haspopup/.test(html)) err('aria-haspopup on the dial — it is a disclosure, not a menu');
for (const m of html.matchAll(/data-short="([^"]*)"/g)) {
  if (m[1].length > 12) err(`data-short "${m[1]}" is over twelve characters`);
}
for (const m of html.matchAll(/<div[^>]*role="tabpanel"[^>]*>/g)) {
  if (!/aria-labelledby="/.test(m[0])) err(`a tabpanel is missing aria-labelledby: ${m[0].slice(0, 60)}…`);
}

// {EXTERNAL LINKS}
const hosts = Array.isArray(allow.value) ? allow.value.map((h) => String(h).toLowerCase()) : [];
const hostOk = (h) => hosts.some((a) => h === a || h.endsWith('.' + a));
for (const m of html.matchAll(/<a\b[^>]*href="(https?:[^"]+)"[^>]*>/g)) {
  let host;
  try { host = new URL(m[1]).hostname.toLowerCase(); } catch { err(`unparseable href ${m[1]}`); continue; }
  if (!hostOk(host)) err(`href host "${host}" is not on the allowlist`);
  if (!/target="_blank"/.test(m[0]) || !/rel="[^"]*noopener/.test(m[0]))
    err(`external anchor without target="_blank" rel="noopener": ${m[1]}`);
}

// {TIMELINE}
const filters = [...html.matchAll(/data-filter="([^"]+)"/g)].map((m) => m[1]);
const liTypes = [...html.matchAll(/<li data-type="([^"]+)"/g)].map((m) => m[1]);
for (const f of filters) {
  if (f === 'all') continue;
  if (!liTypes.includes(f)) err(`filter button "${f}" matches no timeline item — a dead button`);
}
for (const t of new Set(liTypes)) {
  if (filters.length && !filters.includes(t)) err(`timeline data-type "${t}" has no filter button`);
}
// legend covers every type in use, and no others
const legendMatch = html.match(/<div class="legend">([\s\S]*?)<\/div>/);
if (legendMatch && liTypes.length) {
  const legendTypes = [...legendMatch[1].matchAll(/data-type="([^"]+)"/g)].map((m) => m[1]);
  for (const t of new Set(liTypes)) if (!legendTypes.includes(t)) err(`legend is missing data-type "${t}"`);
  for (const t of legendTypes) if (!liTypes.includes(t)) err(`legend names data-type "${t}" that no event uses`);
}

// {STATE TILES} — the shipped no-JS counts must already be true
for (const m of html.matchAll(/<button class="tile[^"]*" type="button" data-state="([^"]+)"[^>]*>\s*<span class="tile-n">(\d+)<\/span>/g)) {
  const [, state, n] = m;
  const g = html.match(new RegExp(
    `<div class="state-group" data-state="${state}">([\\s\\S]*?)(?=<div class="state-group"|</section>)`));
  const actual = g ? (g[1].match(/<div class="row">|<details class="disc(?:"|">)/g) || []).length : 0;
  if (Number(n) !== actual) err(`tile "${state}" says ${n} but its group holds ${actual}`);
}

// {GANTT}
const gantt = html.match(/<div class="gantt"[^>]*>/);
if (gantt) {
  if (!/data-start="\d{4}-\d{2}-\d{2}"/.test(gantt[0])) err('.gantt has no ISO data-start — the runtime cannot place the today line');
  if (!/data-unit="(week|month)"/.test(gantt[0])) err('.gantt has no data-unit="week|month"');
  const colsM = gantt[0].match(/--cols:\s*(\d+)/);
  const cols = colsM ? Number(colsM[1]) : 12;
  const today = count(/class="g-today"/g);
  if (today !== 1) err(`${today} .g-today elements, expected exactly 1 (first child of .g-rows)`);
  else if (!/<ol class="g-rows">\s*<span class="g-today"/.test(html))
    err('.g-today is not the first child of .g-rows');
  for (const m of html.matchAll(/<a class="g-bar[^"]*"[^>]*>([\s\S]*?)<\/a>/g)) {
    const tag = m[0];
    const c1 = tag.match(/--c1:\s*(-?\d+(?:\.\d+)?)/);
    const span = tag.match(/--span:\s*(-?\d+(?:\.\d+)?)/);
    if (!c1 || !span) { err(`a .g-bar is missing --c1/--span: ${tag.slice(0, 80)}…`); continue; }
    for (const [name, v] of [['--c1', c1[1]], ['--span', span[1]]]) {
      if (!/^\d+$/.test(v)) err(`.g-bar ${name}:${v} is not a positive integer`);
    }
    if (Number(c1[1]) < 1 || Number(c1[1]) + Number(span[1]) - 1 > cols)
      err(`.g-bar --c1:${c1[1]} --span:${span[1]} falls outside 1…${cols}`);
    if (!/<span class="vh">[^<]+<\/span>/.test(m[1])) err(`a .g-bar has no .vh sentence: ${tag.slice(0, 80)}…`);
  }
}

// {DISCLOSURES AND GLYPHS}
const discs = count(/<details class="disc/g);
const bodies = count(/class="disc-body"/g);
if (discs !== bodies) err(`${discs} details.disc but ${bodies} .disc-body — every disclosure needs a non-empty body`);
const glyphs = html.match(/[▸▹►▶▾▿✓✔✕✗→←↑↓]/g);
if (glyphs) err(`unicode glyphs where icons belong: ${[...new Set(glyphs)].join(' ')} — every marker comes from the sprites`);

// {TODAY} — Today must be the daily-brief fragment (painting / to-dos / schedule)
// or the explicit .callout.quiet fallback, never a hand-written prose stand-in.
// This is the exact defect a real run produced: panel-today held only <p> prose.
const todayM = html.match(/id="panel-today"[\s\S]*?(?=<div class="panel"|<div class="dial"|<\/main>)/);
if (todayM) {
  const t = todayM[0];
  const hasBrief = /class="(?:frame|herofig|list|sched|ups|reads)\b/.test(t) || /class="[^"]*\bitem\b/.test(t);
  const hasFallback = /class="callout[^"]*\bquiet\b/.test(t);
  if (!hasBrief && !hasFallback)
    err('#panel-today has no daily-brief fragment (no painting, to-dos or schedule) and no .callout.quiet fallback — Today is a hand-written text stand-in; invoke the daily-brief skill for it');
}

// {PREVIEW COVERAGE} — against the rendered HTML (previews built once, above)
const cited = new Set([...html.matchAll(/data-cite="([^"]+)"/g)].map((m) => m[1]));
for (const k of cited) if (!(k in previews)) err(`chip data-cite="${k}" has no #doc-previews entry — a dead hover`);
for (const k of Object.keys(previews)) if (!cited.has(k)) warn(`#doc-previews carries unreferenced key "${k}"`);
// the richness floor wants most resolvable chips hydrated with a preview, not
// left as bare links — a run with many chips and almost no previews under-fetched
const citeTotal = count(/class="cite"/g);
if (citeTotal >= 8 && cited.size / citeTotal < 0.5)
  warn(`only ${cited.size} of ${citeTotal} citation chips carry a preview payload — the richness floor wants most chips hydrated (bake #doc-previews from what you already read to resolve them)`);
// every preview kind must be one the card builder handles — an unknown kind
// still renders (as the generic link card), but it is almost always a typo, so
// warn rather than pass silently
const KINDS = new Set(['pr', 'slack', 'bead', 'cal', 'drive', 'path', 'link']);
for (const [k, v] of Object.entries(previews)) {
  const kind = v && v.kind;
  if (kind && !KINDS.has(kind)) warn(`#doc-previews key "${k}" has unknown kind "${kind}" — it will fall back to the generic link card`);
}

// {PREVIEW QUALITY} — a card resolved to only a title is a half-built card. These
// are the exact defects a real run shipped: PR cards showing author "unknown" with
// no diff, and every avatar falling back to a monogram because no face was fetched.
// A PR always has an author and a diff; their absence means the resolve pass
// stopped at title+state instead of pulling the item's real metadata.
for (const [k, v] of Object.entries(previews)) {
  const p = (v && v.preview) || {};
  const kind = v && v.kind;
  if (kind === 'pr') {
    const miss = ['author', 'additions', 'deletions', 'changedFiles'].filter((f) => p[f] == null);
    if (miss.length)
      err(`PR preview "${k}" is missing ${miss.join(', ')} — the card shows author "unknown" and no diff/files. Fetch them when you resolve the PR (gh pr view <n> --json author,additions,deletions,changedFiles,…) instead of stopping at title+state`);
    if (p.authorAvatarUrl == null)
      warn(`PR preview "${k}" has no authorAvatarUrl — the card falls back to a monogram; download the author's avatar and inline it as a data: URI`);
  }
  if (kind === 'slack' && p.authorAvatarUrl == null)
    warn(`Slack preview "${k}" has no authorAvatarUrl — the face falls back to a monogram; fetch it once and inline it as a data: URI`);
  if (kind === 'drive' && p.ownerAvatarUrl == null)
    warn(`Drive preview "${k}" has no ownerAvatarUrl — inline the owner's face as a data: URI or it shows a monogram`);
}

// {REPORT}
for (const w of warns) console.log(`⚠ ${w}`);
for (const e of errors) console.log(`✗ ${e}`);
console.log(errors.length ? `${errors.length} error(s), ${warns.length} warning(s)` : `clean (${warns.length} warning(s))`);
process.exit(errors.length ? 1 : 0);
